package hmlsb;

import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.FileNotFoundException;
import java.util.PriorityQueue;
import java.util.Scanner;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class Embed extends javax.swing.JFrame {
    
    // init path
    String pathCoverImage = "";
    String pathTxtFile = "";
    
    // init huffman code
    String encodeMsg = "";
    
    // read txt file
    public String readFile(){
        String val = "";
        
        try {
            File myObj = new File(this.pathTxtFile);
            Scanner myReader = new Scanner(myObj);
            
            while(myReader.hasNextLine()){
                String data = myReader.nextLine();
                data = data.replace(" ", "-");
                val = val + data + ",";
            }
            
            myReader.close();
        } catch (FileNotFoundException e) {
            System.out.println(e);
        }
        
        return val;
    }

    /**
     * Creates new form Embed
     */
    public Embed() {
        initComponents();
        this.setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnCoverImage = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnMessage = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnEmbed = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        showImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Sistem Penyisipan Data Teks - Embed");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(34, 45, 65));

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Embed Pesan");

        btnCoverImage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCoverImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCoverImageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCoverImageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCoverImageMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnCoverImageMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        jLabel2.setText("PILIH COVER IMAGE");

        javax.swing.GroupLayout btnCoverImageLayout = new javax.swing.GroupLayout(btnCoverImage);
        btnCoverImage.setLayout(btnCoverImageLayout);
        btnCoverImageLayout.setHorizontalGroup(
            btnCoverImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
            .addGroup(btnCoverImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnCoverImageLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnCoverImageLayout.setVerticalGroup(
            btnCoverImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(btnCoverImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnCoverImageLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        btnMessage.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMessage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMessageMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnMessageMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnMessageMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnMessageMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        jLabel3.setText("PILIH PESAN (.TXT)");

        javax.swing.GroupLayout btnMessageLayout = new javax.swing.GroupLayout(btnMessage);
        btnMessage.setLayout(btnMessageLayout);
        btnMessageLayout.setHorizontalGroup(
            btnMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
            .addGroup(btnMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnMessageLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnMessageLayout.setVerticalGroup(
            btnMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(btnMessageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnMessageLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        btnEmbed.setBackground(new java.awt.Color(110, 217, 161));
        btnEmbed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEmbed.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEmbedMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Poppins Medium", 0, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("EMBED PESAN");

        javax.swing.GroupLayout btnEmbedLayout = new javax.swing.GroupLayout(btnEmbed);
        btnEmbed.setLayout(btnEmbedLayout);
        btnEmbedLayout.setHorizontalGroup(
            btnEmbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 125, Short.MAX_VALUE)
            .addGroup(btnEmbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnEmbedLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        btnEmbedLayout.setVerticalGroup(
            btnEmbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
            .addGroup(btnEmbedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(btnEmbedLayout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jLabel6.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Silahkan pilih gambar dan file pesan");

        jLabel7.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("yang akan di sisipkan");

        showImage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCoverImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnMessage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(btnEmbed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(140, 140, 140)
                    .addComponent(showImage, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(140, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMessage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCoverImage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEmbed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(145, 145, 145)
                    .addComponent(showImage, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addGap(145, 145, 145)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCoverImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCoverImageMouseClicked
//        JFileChooser chooser = new JFileChooser();
//        chooser.showOpenDialog(null);
//        File file = chooser.getSelectedFile();
//        this.pathCoverImage = file.toString();
        try{
            JFileChooser chooser = new JFileChooser();
            chooser.showOpenDialog(null);
            File file = chooser.getSelectedFile();
            this.pathCoverImage = file.toString();
            Image img = ImageIO.read(file);
            Image newImg = img.getScaledInstance(showImage.getWidth(), showImage.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(newImg);
            showImage.setIcon(icon);
        }catch (Exception e){
            System.out.println("Terjadi sebuah kesalahan!");
            System.out.println(e);
        }
    }//GEN-LAST:event_btnCoverImageMouseClicked

    private void btnMessageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMessageMouseClicked
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        this.pathTxtFile = file.toString();
    }//GEN-LAST:event_btnMessageMouseClicked

    private void btnEmbedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEmbedMouseClicked
        HuffmanModule hm = new HuffmanModule();
        LsbModule lsb = new LsbModule();
        
        String plaintext = readFile();        
        String character_plaintext = hm.getCharacter(plaintext);
        char character[] = character_plaintext.toCharArray();
        int frequency[] = new int[character_plaintext.length()];
        for(int i=0; i<character_plaintext.length(); i++){
            frequency[i] = hm.getFreqency(plaintext, character_plaintext.charAt(i));
        }
        
        hm.sortByFrequency(character, frequency);
        
        // create tree
        int n = character.length;
        PriorityQueue<HuffmanNode> q = new PriorityQueue<HuffmanNode>(n, new ImplementComparator());
        
        for(int i=0; i<n; i++){
            HuffmanNode hn = new HuffmanNode();
            
            hn.c = character[i];
            hn.item = frequency[i];
            
            hn.left = null;
            hn.right = null;
            
            q.add(hn);
        }
        
        HuffmanNode root = null;
        
        while(q.size() > 1){
            HuffmanNode x = q.peek();
            q.poll();
            
            HuffmanNode y = q.peek();
            q.poll();
            
            HuffmanNode f = new HuffmanNode();
            
            f.item = x.item + y.item;
            f.c = '-';
            f.left = x;
            f.right = y;
            root = f;
            
            q.add(f);
        }
        
        hm.printCode(root, "");
        
        // print output
        this.encodeMsg = hm.encode(hm.character, hm.code, plaintext);
        String nEncodeMsg = this.encodeMsg.length() + "";
        // System.out.println(plaintext + " = " + this.encode);
        
        // embed msg to image
        try {
            String pathOutput = "C:\\Users\\Syahrul\\Documents\\Hasil Data\\Embed\\Hasil Foto Stego\\stego.png";
            lsb.embed(this.pathCoverImage, pathOutput, this.encodeMsg);
            JOptionPane.showMessageDialog(this, "Stego Image berhasil disimpan di " + pathOutput);
        } catch (Exception e){
            System.out.println(e);
        }
        
        // write huffman code
        try {
            String pathOutput = "C:\\Users\\Syahrul\\Documents\\Hasil Data\\Embed\\HuffmanKey\\huffmancode.txt";
            FileWriter myWriter = new FileWriter(pathOutput);
            myWriter.write(hm.character);
            myWriter.write("\n");
            myWriter.write(hm.code);
            myWriter.write("\n");
            myWriter.write(nEncodeMsg);
            myWriter.close();
        } catch (IOException e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnEmbedMouseClicked

    private void btnCoverImageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCoverImageMouseEntered
        btnCoverImage.setBackground(new Color(227, 227, 227));
    }//GEN-LAST:event_btnCoverImageMouseEntered

    private void btnCoverImageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCoverImageMouseExited
        btnCoverImage.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_btnCoverImageMouseExited

    private void btnCoverImageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCoverImageMousePressed
        btnCoverImage.setBackground(new Color(215, 215, 215));
    }//GEN-LAST:event_btnCoverImageMousePressed

    private void btnMessageMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMessageMouseEntered
        btnMessage.setBackground(new Color(227, 227, 227));
    }//GEN-LAST:event_btnMessageMouseEntered

    private void btnMessageMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMessageMouseExited
        btnMessage.setBackground(new Color(240, 240, 240));
    }//GEN-LAST:event_btnMessageMouseExited

    private void btnMessageMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMessageMousePressed
        btnMessage.setBackground(new Color(215, 215, 215));
    }//GEN-LAST:event_btnMessageMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Embed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Embed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Embed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Embed.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Embed().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnCoverImage;
    private javax.swing.JPanel btnEmbed;
    private javax.swing.JPanel btnMessage;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel showImage;
    // End of variables declaration//GEN-END:variables
}
